steps:
    # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/easybalance-frontend:latest', '.']

    # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/easybalance-frontend:latest']

    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'easybalance-frontend', '--image', 'gcr.io/$PROJECT_ID/easybalance-frontend:latest', '--region', 'us-central1', '--port', '3000']

# Using NONE to minimize the costs but it's recommended to use at least "GCS_ONLY" (Cloud Storage) or "CLOUD_LOGGING_ONLY" (Cloud Logging)
options:
  logging: NONE